// src/lib/data.ts

export const promptsData = [
  // ========================================
  // KATEGORI: BISNIS
  // ========================================
  {
    id: "1",
    title: "Cold Email Penawaran Jasa SEO",
    cover: "/images/covers/bisnis-category.png",
    slug: "cold-email-seo",
    category: "bisnis",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Template email dingin untuk menawarkan jasa SEO ke pemilik bisnis lokal.",
    content: "Subjek: Ide untuk meningkatkan traffic [Nama Perusahaan]\n\nHalo [Nama],\n\nSaya baru saja melihat website Anda dan sangat suka dengan [Sebutkan hal spesifik]. Namun, saya melihat ada peluang besar untuk meningkatkan peringkat di Google untuk kata kunci [Kata Kunci].\n\nBerdasarkan analisis singkat, saya menemukan bahwa [Sebutkan 2-3 masalah SEO spesifik]. Dengan optimasi yang tepat, Anda bisa mendapatkan traffic organik 2-3x lipat dalam 3-6 bulan.\n\nApakah Anda tertarik untuk mendiskusikan strategi SEO yang bisa diterapkan untuk bisnis Anda? Saya siap melakukan audit gratis untuk website Anda.\n\nSalam,\n[Nama Anda]\n[Posisi]\n[Perusahaan]\n[Website]\n[Telepon]",
  },
  {
    id: "2",
    title: "Analisis SWOT Produk Baru",
    cover: "/images/covers/bisnis-category.png",
    slug: "analisis-swot",
    category: "bisnis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Prompt komprehensif untuk menganalisis kekuatan dan kelemahan ide bisnis.",
    content: "Bantu saya melakukan analisis SWOT untuk ide bisnis berikut: [Jelaskan Ide Bisnis]. Berikan daftar detail untuk Strengths, Weaknesses, Opportunities, dan Threats. Berikan juga strategi mitigasi untuk setiap ancaman.\n\nStrengths (Kekuatan):\n- Apa keunggulan kompetitif produk ini?\n- Apa yang membuat produk ini unik?\n- Apa sumber daya yang dimiliki?\n\nWeaknesses (Kelemahan):\n- Apa kekurangan produk ini?\n- Apa hambatan yang mungkin dihadapi?\n- Apa yang perlu diperbaiki?\n\nOpportunities (Peluang):\n- Apa tren pasar yang bisa dimanfaatkan?\n- Apa celah pasar yang belum terlayani?\n- Apa peluang ekspansi?\n\nThreats (Ancaman):\n- Apa kompetitor utama?\n- Apa risiko pasar?\n- Apa faktor eksternal yang mengancam?\n\nStrategi Mitigasi:\n- Bagaimana mengatasi setiap ancaman?\n- Apa rencana cadangan?",
  },
  {
    id: "3",
    title: "Business Plan Executive Summary",
    cover: "/images/covers/bisnis-category.png",
    slug: "business-plan-summary",
    category: "bisnis",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Buat ringkasan eksekutif untuk business plan startup.",
    content: "Tulis executive summary untuk business plan startup [Nama Startup] di industri [Industri]. Startup ini menawarkan [Jelaskan produk/layanan] untuk menyelesaikan masalah [Jelaskan masalah].\n\nSertakan:\n1. Visi dan misi perusahaan\n2. Problem statement (masalah yang dipecahkan)\n3. Solusi yang ditawarkan\n4. Target market dan ukuran pasar\n5. Model bisnis dan revenue streams\n6. Competitive advantage\n7. Tim pendiri (jika ada)\n8. Funding requirements (jika ada)\n9. Proyeksi pertumbuhan 3 tahun\n\nGunakan bahasa profesional namun mudah dipahami. Panjang sekitar 1-2 halaman.",
  },
  {
    id: "4",
    title: "Pitch Deck Investor",
    cover: "/images/covers/bisnis-category.png",
    slug: "pitch-deck-investor",
    category: "bisnis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Template pitch deck untuk presentasi ke investor.",
    content: "Buat outline pitch deck untuk startup [Nama Startup] yang mencari funding [Jumlah]. Startup ini bergerak di bidang [Industri] dengan produk [Jelaskan produk].\n\nSlide 1: Cover - Nama startup, tagline, logo\nSlide 2: Problem - Masalah besar yang dipecahkan\nSlide 3: Solution - Solusi yang ditawarkan\nSlide 4: Market Size - Ukuran pasar dan potensi\nSlide 5: Product - Demo produk atau fitur utama\nSlide 6: Business Model - Cara menghasilkan uang\nSlide 7: Traction - Milestone yang sudah dicapai\nSlide 8: Competition - Landscape kompetitor\nSlide 9: Team - Profil tim pendiri\nSlide 10: Financials - Proyeksi keuangan 3 tahun\nSlide 11: Ask - Jumlah funding dan penggunaan dana\nSlide 12: Contact - Informasi kontak\n\nBerikan poin-poin kunci untuk setiap slide dengan data yang konkret.",
  },
  {
    id: "5",
    title: "Financial Projection Template",
    cover: "/images/covers/bisnis-category.png",
    slug: "financial-projection",
    category: "bisnis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Template proyeksi keuangan untuk startup atau bisnis baru.",
    content: "Buat proyeksi keuangan 3 tahun untuk bisnis [Jenis Bisnis] dengan asumsi berikut:\n\nRevenue Streams:\n- [Sumber pendapatan 1]: [Proyeksi bulanan]\n- [Sumber pendapatan 2]: [Proyeksi bulanan]\n- [Sumber pendapatan 3]: [Proyeksi bulanan]\n\nCost Structure:\n- Fixed Costs (biaya tetap): [Daftar biaya tetap]\n- Variable Costs (biaya variabel): [Daftar biaya variabel]\n- COGS (Cost of Goods Sold): [Persentase atau nominal]\n\nKey Metrics:\n- Customer Acquisition Cost (CAC)\n- Lifetime Value (LTV)\n- Gross Margin\n- Burn Rate\n- Break-even Point\n\nBuat dalam format tabel bulanan untuk tahun pertama, lalu kuartalan untuk tahun kedua dan ketiga. Sertakan asumsi yang digunakan untuk setiap proyeksi.",
  },

  // ========================================
  // KATEGORI: MARKETING
  // ========================================
  {
    id: "6",
    title: "Framework Copywriting PAS",
    cover: "/images/covers/marketing-category.png",
    slug: "framework-pas",
    category: "marketing",
    rekomAI: [ "ChatGPT", "Jasper", "Writesonic" ],
    description: "Prompt untuk membuat copy iklan menggunakan metode Problem-Agitation-Solution.",
    content: "Bertindaklah sebagai copywriter senior. Buatkan saya teks iklan Facebook untuk produk [Nama Produk] yang menargetkan [Target Audience]. Gunakan kerangka kerja PAS (Problem, Agitation, Solution). Pastikan nada bicaranya empatik namun persuasif.\n\nProblem: Identifikasi masalah utama yang dihadapi target audience\nAgitation: Perjelas rasa sakit atau frustrasi dari masalah tersebut\nSolution: Perkenalkan produk sebagai solusi yang sempurna\n\nFormat output:\n1. Headline (maksimal 50 karakter)\n2. Primary Text (maksimal 125 karakter)\n3. Description (maksimal 30 karakter)\n4. Call-to-Action yang kuat",
  },
  {
    id: "7",
    title: "Social Media Content Calendar",
    cover: "/images/covers/marketing-category.png",
    slug: "content-calendar",
    category: "marketing",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Buat kalender konten media sosial untuk 1 bulan.",
    content: "Buat content calendar untuk [Nama Brand/Bisnis] di platform [Instagram/Facebook/TikTok/LinkedIn] untuk bulan depan.\n\nBrand Info:\n- Industri: [Industri]\n- Target Audience: [Demografi target]\n- Tone of Voice: [Formal/Santai/Profesional/Kreatif]\n- Goals: [Awareness/Sales/Engagement]\n\nBuat 15-20 konten dengan format:\n- Tanggal\n- Platform\n- Jenis Konten (Reels/Post/Story/Carousel)\n- Topik/Theme\n- Caption (maksimal 150 kata)\n- Hashtags (5-10 relevant hashtags)\n- CTA (Call-to-Action)\n- Visual suggestion\n\nSertakan mix konten: educational, promotional, entertaining, dan user-generated content.",
  },
  {
    id: "8",
    title: "Email Marketing Sequence",
    cover: "/images/covers/marketing-category.png",
    slug: "email-sequence",
    category: "marketing",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat sequence email marketing untuk welcome series atau nurture campaign.",
    content: "Buat email sequence untuk [Tujuan: welcome series/nurture campaign/sales funnel] untuk [Nama Bisnis/Product].\n\nSequence Details:\n- Jumlah email: [5-7 emails]\n- Timeline: [Contoh: Day 1, Day 3, Day 7, Day 14, Day 21]\n- Goal: [Convert leads/build trust/promote product]\n\nUntuk setiap email, sertakan:\n1. Subject line (maksimal 50 karakter)\n2. Preheader text (maksimal 100 karakter)\n3. Email body (300-500 kata)\n4. CTA button text\n5. Personalization tokens ([nama], [perusahaan], dll)\n\nPastikan alur cerita yang konsisten dan value yang jelas di setiap email.",
  },
  {
    id: "9",
    title: "SEO Keyword Research",
    cover: "/images/covers/marketing-category.png",
    slug: "seo-keyword-research",
    category: "marketing",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat daftar keyword SEO untuk niche atau topik tertentu.",
    content: "Lakukan keyword research untuk topik [Topik/Niche] dengan fokus pada [Target Audience/Lokasi].\n\nOutput yang diinginkan:\n1. Primary Keywords (5-10 keywords)\n   - Volume pencarian (estimasi)\n   - Competition level (low/medium/high)\n   - Intent (informational/commercial/transactional)\n\n2. Long-tail Keywords (15-20 keywords)\n   - Question-based keywords\n   - Location-based keywords\n   - Problem-solving keywords\n\n3. Related Topics & Entities\n   - Topik terkait yang bisa dikembangkan\n   - Entities penting dalam niche ini\n\n4. Content Gap Analysis\n   - Topik yang belum banyak dibahas kompetitor\n   - Opportunity keywords dengan volume tinggi dan competition rendah\n\nFormat dalam tabel dengan kolom: Keyword, Volume, Competition, Intent, Difficulty Score.",
  },
  {
    id: "10",
    title: "Landing Page Copy",
    cover: "/images/covers/marketing-category.png",
    slug: "landing-page-copy",
    category: "marketing",
    rekomAI: [ "ChatGPT", "Jasper", "Copy.ai" ],
    description: "Buat copy landing page yang konversi tinggi untuk produk atau layanan.",
    content: "Tulis landing page copy untuk [Nama Produk/Layanan] yang menargetkan [Target Audience].\n\nPage Structure:\n1. Hero Section\n   - Headline (maksimal 10 kata, benefit-driven)\n   - Subheadline (maksimal 20 kata, klarifikasi)\n   - Primary CTA button text\n\n2. Problem Section\n   - Identifikasi masalah audiens\n   - Agitate the pain points\n\n3. Solution Section\n   - Perkenalkan produk sebagai solusi\n   - Unique Value Proposition\n\n4. Features/Benefits Section\n   - 3-5 fitur utama dengan benefit masing-masing\n   - Gunakan format: Feature → Benefit → Proof\n\n5. Social Proof Section\n   - Testimonial template\n   - Stats/numbers yang impressive\n   - Trust badges/logos\n\n6. Pricing Section\n   - Tier descriptions\n   - Value justification\n\n7. FAQ Section\n   - 5-7 pertanyaan umum dengan jawaban\n\n8. Final CTA Section\n   - Urgency/scarcity element\n   - Guarantee/risk reversal\n   - Final CTA\n\nTone: [Profesional/Santai/Energetic/Empathetic]",
  },

  // ========================================
  // KATEGORI: KREATIF
  // ========================================
  {
    id: "11",
    title: "Cerita Pendek Inspiratif",
    cover: "/images/covers/kreatif-category.png",
    slug: "cerita-pendek-inspiratif",
    category: "kreatif",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Buat cerita pendek dengan tema motivasi dan inspirasi.",
    content: "Tulis cerita pendek (800-1000 kata) dengan tema [Tema: ketekunan/mimpi/persahabatan/keberanian].\n\nKarakter Utama:\n- Nama: [Nama karakter]\n- Usia: [Usia]\n- Profesi/Latar belakang: [Deskripsi]\n- Konflik internal: [Masalah pribadi]\n\nSetting:\n- Lokasi: [Tempat cerita berlangsung]\n- Waktu: [Periode waktu]\n- Atmosfer: [Suasana yang ingin diciptakan]\n\nPlot Structure:\n1. Opening - Perkenalkan karakter dan situasi awal\n2. Inciting Incident - Kejadian yang memulai konflik\n3. Rising Action - Perkembangan masalah\n4. Climax - Titik balik atau keputusan penting\n5. Falling Action - Konsekuensi dari keputusan\n6. Resolution - Penyelesaian dan pelajaran\n\nElemen yang harus ada:\n- Dialog yang natural\n- Deskripsi sensorik (visual, suara, bau, dll)\n- Emosi yang berkembang\n- Twist atau surprise element (opsional)\n- Moral/lesson yang jelas namun tidak menggurui\n\nTone: [Heartwarming/Inspirational/Thought-provoking]",
  },
  {
    id: "12",
    title: "Puisi Modern",
    cover: "/images/covers/kreatif-category.png",
    slug: "puisi-modern",
    category: "kreatif",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Buat puisi modern dengan tema dan gaya tertentu.",
    content: "Tulis puisi modern dengan tema [Tema: cinta/alam/kehidupan/kota/waktu].\n\nSpesifikasi:\n- Jumlah bait: [3-5 bait]\n- Gaya: [Free verse/Haiku/Sonnet/Concrete poetry]\n- Mood: [Melankolis/Riang/Reflektif/Misterius]\n- Imagery: [Visual/Auditory/Tactile/Metaphorical]\n\nElemen puisi:\n1. Opening line yang kuat dan menarik\n2. Penggunaan metafora dan simile\n3. Rhythm dan flow yang natural\n4. Enjambment (opsional)\n5. Closing line yang memorable\n\nHindari:\n- Klise dan cliché\n- Rima yang terlalu kaku\n- Bahasa yang terlalu literal\n\nContoh tema spesifik:\n- \"Kota yang tidak pernah tidur\"\n- \"Hujan di pagi hari\"\n- \"Kenangan yang memudar\"\n- \"Harapan di tengah kegelapan\"",
  },
  {
    id: "13",
    title: "Script Video Pendek",
    cover: "/images/covers/kreatif-category.png",
    slug: "script-video-pendek",
    category: "kreatif",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat script untuk video pendek (TikTok/Reels/Shorts).",
    content: "Tulis script video pendek durasi [Durasi: 30-60 detik] untuk platform [TikTok/Instagram Reels/YouTube Shorts].\n\nVideo Details:\n- Niche/Topic: [Topik video]\n- Target Audience: [Demografi]\n- Goal: [Entertain/Educate/Promote]\n- Style: [Comedic/Serious/Inspirational]\n\nScript Format:\n[0:00-0:03] HOOK - Opening yang menarik perhatian\n[0:03-0:10] SETUP - Perkenalkan topik/masalah\n[0:10-0:25] CONTENT - Isi utama (tips/story/reveal)\n[0:25-0:35] PAYOFF - Twist atau poin utama\n[0:35-0:45] CTA - Call-to-action\n[0:45-0:60] OUTRO - Closing dan branding\n\nSertakan:\n- Visual cues (gerakan kamera, transisi)\n- Text overlay suggestions\n- Music/sound effect recommendations\n- Caption untuk posting\n- Hashtags yang relevan\n\nHook harus sangat kuat dalam 3 detik pertama untuk mencegah scroll away.",
  },
  {
    id: "14",
    title: "Character Development",
    cover: "/images/covers/kreatif-category.png",
    slug: "character-development",
    category: "kreatif",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat karakter fiksi yang kompleks dan believable.",
    content: "Kembangkan karakter fiksi untuk [Genre: fantasy/sci-fi/romance/thriller/drama].\n\nBasic Info:\n- Nama: [Nama karakter]\n- Usia: [Usia]\n- Gender: [Gender]\n- Pekerjaan/Role: [Profesi atau peran dalam cerita]\n\nPhysical Description:\n- Appearance (tinggi, berat, warna rambut/mata, ciri khas)\n- Style (cara berpakaian, grooming)\n- Mannerisms (gerakan khas, kebiasaan)\n\nPersonality:\n- Strengths (3-5 kekuatan karakter)\n- Weaknesses (3-5 kelemahan/flaws)\n- Quirks (kebiasaan unik)\n- Fears (ketakutan terbesar)\n- Motivations (apa yang mendorong karakter)\n\nBackstory:\n- Childhood (masa kecil yang membentuk karakter)\n- Key Events (peristiwa penting dalam hidupnya)\n- Relationships (hubungan dengan karakter lain)\n- Trauma/Wounds (luka emosional masa lalu)\n\nCharacter Arc:\n- Starting Point (siapa karakter di awal cerita)\n- Growth/Change (bagaimana karakter berkembang)\n- End Point (siapa karakter di akhir cerita)\n\nDialogue Style:\n- Vocabulary level\n- Speech patterns\n- Catchphrases (jika ada)\n\nInternal Conflict:\n- Apa dilema moral yang dihadapi?\n- Apa yang ingin vs apa yang seharusnya dilakukan?\n\nExternal Conflict:\n- Siapa/apa yang menjadi antagonis?\n- Apa tantangan eksternal yang dihadapi?",
  },
  {
    id: "15",
    title: "World Building Fantasy",
    cover: "/images/covers/kreatif-category.png",
    slug: "world-building-fantasy",
    category: "kreatif",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat dunia fiksi yang detail dan immersive untuk cerita fantasy.",
    content: "Bangun dunia fiksi untuk cerita [Genre: high fantasy/urban fantasy/sci-fi] dengan setting [Setting: medieval/futuristic/alternate reality].\n\nGeography & Environment:\n- Continent/Region names\n- Climate and weather patterns\n- Natural resources\n- Flora and fauna (termasuk makhluk mitos jika ada)\n- Landmarks dan lokasi penting\n\nHistory & Timeline:\n- Creation myth/origin story\n- Major historical events\n- Wars and conflicts\n- Golden ages and dark ages\n- Current timeline position\n\nSociety & Culture:\n- Government system\n- Social hierarchy/classes\n- Religion and beliefs\n- Traditions and customs\n- Arts and entertainment\n- Education system\n\nTechnology & Magic:\n- Technology level\n- Magic system (rules, limitations, sources)\n- Tools and weapons\n- Transportation\n- Communication methods\n\nEconomy & Trade:\n- Currency system\n- Major industries\n- Trade routes\n- Wealth distribution\n\nPolitics & Power:\n- Factions and guilds\n- Power struggles\n- Laws and justice system\n- International relations\n\nDaily Life:\n- Food and cuisine\n- Clothing and fashion\n- Housing and architecture\n- Family structures\n- Work and occupations\n\nConflicts & Tensions:\n- Current problems\n- Social issues\n- External threats\n- Internal divisions\n\nMap Description:\n- Major cities and their characteristics\n- Geographic boundaries\n- Strategic locations\n\nBuat world bible yang bisa digunakan sebagai referensi konsisten untuk penulisan cerita.",
  },

  // ========================================
  // KATEGORI: TEKNIS
  // ========================================
  {
    id: "16",
    title: "Code Review & Optimization",
    cover: "/images/covers/teknis-category.png",
    slug: "code-review-optimization",
    category: "teknis",
    rekomAI: [ "ChatGPT", "Claude", "GitHub Copilot" ],
    description: "Review dan optimasi kode programming untuk performa dan best practices.",
    content: "Review kode berikut dan berikan feedback:\n\n```[Bahasa Pemrograman]\n[Kode yang ingin direview]\n```\n\nAspek yang perlu dianalisis:\n1. Code Quality\n   - Readability dan maintainability\n   - Naming conventions\n   - Code duplication\n   - Comment quality\n\n2. Performance\n   - Time complexity analysis\n   - Memory usage optimization\n   - Bottlenecks identification\n   - Caching opportunities\n\n3. Security\n   - Potential vulnerabilities\n   - Input validation\n   - SQL injection risks\n   - XSS/CSRF protection\n\n4. Best Practices\n   - Design patterns yang sesuai\n   - SOLID principles compliance\n   - Error handling\n   - Logging implementation\n\n5. Refactoring Suggestions\n   - Specific code improvements\n   - Alternative approaches\n   - Code examples untuk perbaikan\n\n6. Testing Recommendations\n   - Unit test cases yang perlu ditambahkan\n   - Integration test scenarios\n   - Edge cases to consider\n\nBerikan prioritas untuk critical issues terlebih dahulu, lalu suggestions untuk improvement.",
  },
  {
    id: "17",
    title: "API Documentation Generator",
    cover: "/images/covers/teknis-category.png",
    slug: "api-documentation",
    category: "teknis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat dokumentasi API yang lengkap dan mudah dipahami.",
    content: "Buat dokumentasi API untuk endpoint berikut:\n\nAPI Info:\n- Base URL: [Base URL API]\n- Version: [Version number]\n- Authentication: [API key/OAuth2/JWT/Bearer token]\n\nEndpoint: [HTTP Method] [Endpoint URL]\n\nRequest:\n- Headers (required dan optional)\n- Query Parameters (dengan type, required status, description)\n- Path Parameters (dengan type, required status, description)\n- Request Body (JSON schema dengan field descriptions)\n\nResponse:\n- Success Response (200/201)\n  * Status code dan message\n  * Response body structure\n  * Example response\n\n- Error Responses\n  * 400 Bad Request (validation errors)\n  * 401 Unauthorized\n  * 403 Forbidden\n  * 404 Not Found\n  * 500 Internal Server Error\n  * Example error responses\n\nUsage Examples:\n- cURL example\n- JavaScript (fetch) example\n- Python (requests) example\n- PHP example\n\nRate Limiting:\n- Limits per time period\n- Headers untuk rate limit info\n\nVersioning:\n- Breaking changes dari versi sebelumnya\n- Migration guide (jika ada)\n\nFormat dokumentasi harus jelas, terstruktur, dan include code examples yang bisa langsung digunakan.",
  },
  {
    id: "18",
    title: "Database Schema Design",
    cover: "/images/covers/teknis-category.png",
    slug: "database-schema-design",
    category: "teknis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Rancang database schema untuk aplikasi atau sistem tertentu.",
    content: "Rancang database schema untuk aplikasi [Jenis Aplikasi: e-commerce/social media/blog/CMS] dengan requirement berikut:\n\nFunctional Requirements:\n- [Requirement 1]\n- [Requirement 2]\n- [Requirement 3]\n\nEntities yang diperlukan:\n1. [Entity Name]\n   - Fields (dengan type, constraints, default values)\n   - Primary key\n   - Foreign keys (relationships)\n   - Indexes yang diperlukan\n\n2. [Entity Name]\n   - Fields (dengan type, constraints, default values)\n   - Primary key\n   - Foreign keys (relationships)\n   - Indexes yang diperlukan\n\n[... tambahkan entity lainnya]\n\nRelationships:\n- One-to-One relationships\n- One-to-Many relationships\n- Many-to-Many relationships (dengan junction tables)\n\nDatabase Type: [MySQL/PostgreSQL/MongoDB/etc]\n\nOutput yang diinginkan:\n1. ER Diagram description (text-based)\n2. CREATE TABLE statements untuk setiap table\n3. Sample INSERT queries untuk testing\n4. Common JOIN queries yang akan sering digunakan\n5. Index recommendations untuk optimization\n6. Normalization level (1NF, 2NF, 3NF, BCNF)\n\nConsiderations:\n- Scalability requirements\n- Data integrity constraints\n- Performance optimization\n- Backup and recovery strategy",
  },
  {
    id: "19",
    title: "Algorithm Implementation",
    cover: "/images/covers/teknis-category.png",
    slug: "algorithm-implementation",
    category: "teknis",
    rekomAI: [ "ChatGPT", "Claude", "GitHub Copilot" ],
    description: "Implementasi algoritma dengan bahasa pemrograman tertentu.",
    content: "Implementasikan algoritma [Nama Algoritma: sorting/searching/graph/dynamic programming] dalam bahasa [Bahasa Pemrograman].\n\nRequirements:\n- Input: [Deskripsi input format dan constraints]\n- Output: [Deskripsi output yang diharapkan]\n- Time Complexity: [Target complexity, contoh: O(n log n)]\n- Space Complexity: [Target complexity, contoh: O(n)]\n\nImplementation Details:\n1. Function signature dengan parameter yang jelas\n2. Input validation dan error handling\n3. Core algorithm logic dengan comments yang menjelaskan setiap step\n4. Edge cases handling\n5. Test cases (minimal cases, edge cases, large input cases)\n\nCode Structure:\n- Modular functions jika memungkinkan\n- Helper functions untuk sub-tasks\n- Clear variable naming\n- Comprehensive comments\n\nExample Usage:\n- Sample input dan expected output\n- How to call the function\n- Performance benchmark (jika relevan)\n\nOptimization Notes:\n- Potential improvements\n- Alternative approaches\n- Trade-offs between different implementations\n\nDocumentation:\n- Function description\n- Parameter descriptions\n- Return value description\n- Time and space complexity analysis\n- References (jika ada)",
  },
  {
    id: "20",
    title: "System Architecture Design",
    cover: "/images/covers/teknis-category.png",
    slug: "system-architecture-design",
    category: "teknis",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Rancang arsitektur sistem untuk aplikasi scalable dan robust.",
    content: "Rancang system architecture untuk [Jenis Aplikasi/Sistem] dengan requirement:\n\nScale Requirements:\n- Expected users: [Jumlah]\n- Requests per second: [RPS]\n- Data volume: [Size]\n- Availability target: [Contoh: 99.9%]\n\nFunctional Requirements:\n- [Requirement 1]\n- [Requirement 2]\n- [Requirement 3]\n\nNon-Functional Requirements:\n- Performance: [Latency targets]\n- Scalability: [Horizontal/Vertical scaling needs]\n- Security: [Compliance requirements]\n- Reliability: [Fault tolerance needs]\n\nArchitecture Components:\n1. Client Layer\n   - Web frontend technology\n   - Mobile app considerations\n   - CDN requirements\n\n2. API Gateway Layer\n   - Load balancing strategy\n   - Rate limiting\n   - Authentication/Authorization\n   - Caching layer\n\n3. Application Layer\n   - Microservices vs Monolith decision\n   - Service boundaries\n   - Communication patterns (REST/gRPC/Message Queue)\n   - State management\n\n4. Data Layer\n   - Database selection (SQL vs NoSQL)\n   - Data partitioning/sharding strategy\n   - Replication and backup\n   - Caching strategy (Redis/Memcached)\n\n5. Infrastructure\n   - Cloud provider (AWS/Azure/GCP)\n   - Containerization (Docker/Kubernetes)\n   - CI/CD pipeline\n   - Monitoring and logging\n\n6. Security\n   - Network security (firewalls, VPC)\n   - Data encryption (at rest, in transit)\n   - Authentication mechanisms\n   - Audit logging\n\nOutput:\n- Architecture diagram description\n- Technology stack recommendations\n- Deployment strategy\n- Scaling strategy\n- Disaster recovery plan\n- Cost estimation considerations",
  },

  // ========================================
  // KATEGORI: EDUKASI
  // ========================================
  {
    id: "21",
    title: "Lesson Plan Generator",
    cover: "/images/covers/edukasi-category.png",
    slug: "lesson-plan-generator",
    category: "edukasi",
    rekomAI: [ "ChatGPT", "Claude", "Bard" ],
    description: "Buat lesson plan yang komprehensif untuk mata pelajaran tertentu.",
    content: "Buat lesson plan untuk [Mata Pelajaran] kelas [Level: SD/SMP/SMA/Kuliah] dengan topik [Topik Pembelajaran].\n\nLesson Details:\n- Duration: [Durasi: 45 menit/90 menit/2 jam]\n- Learning Objectives:\n  * Siswa akan mampu [Objective 1]\n  * Siswa akan memahami [Objective 2]\n  * Siswa akan dapat [Objective 3]\n\nMaterials Needed:\n- [Daftar bahan/alat yang diperlukan]\n- Technology requirements\n- Handouts atau worksheets\n\nLesson Structure:\n\n1. Introduction (10% dari waktu)\n   - Hook/attention grabber\n   - Review materi sebelumnya\n   - State learning objectives\n   - Connect to real-world applications\n\n2. Direct Instruction (25% dari waktu)\n   - Key concepts explanation\n   - Examples and demonstrations\n   - Visual aids suggestions\n   - Important vocabulary/terms\n\n3. Guided Practice (30% dari waktu)\n   - Interactive activities\n   - Group work or pair work\n   - Teacher facilitation steps\n   - Common misconceptions to address\n\n4. Independent Practice (25% dari waktu)\n   - Individual assignments\n   - Differentiated activities (untuk berbagai level)\n   - Extension activities (untuk siswa cepat)\n\n5. Assessment & Closure (10% dari waktu)\n   - Formative assessment methods\n   - Exit ticket or quick quiz\n   - Summary of key points\n   - Preview next lesson\n\nAssessment Methods:\n- Formative: [Quizzes/observations/discussions]\n- Summative: [Tests/projects/presentations]\n- Rubrics atau scoring guides\n\nDifferentiation Strategies:\n- For struggling students\n- For advanced students\n- For ELL (English Language Learners)\n- For students with special needs\n\nHomework Assignment:\n- Purpose and expectations\n- Instructions yang jelas\n- Due date\n\nReflection Questions:\n- What worked well?\n- What needs improvement?\n- Student engagement level\n- Time management",
  },
  {
    id: "22",
    title: "Interactive Quiz Creator",
    cover: "/images/covers/edukasi-category.png",
    slug: "interactive-quiz-creator",
    category: "edukasi",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat kuis interaktif dengan berbagai jenis pertanyaan.",
    content: "Buat kuis interaktif untuk topik [Topik] dengan level kesulitan [Mudah/Sedang/Sulit].\n\nQuiz Specifications:\n- Total questions: [10-20 questions]\n- Time limit: [Jika ada]\n- Passing score: [Persentase]\n\nQuestion Types (mix dari berbagai jenis):\n\n1. Multiple Choice Questions (40%)\n   - 4 options per question\n   - 1 correct answer\n   - Distractors yang plausible\n   - Explanation untuk jawaban benar\n\n2. True/False Questions (20%)\n   - Clear statements\n   - Common misconceptions sebagai false statements\n   - Brief explanations\n\n3. Fill-in-the-Blank Questions (15%)\n   - Key terms atau concepts\n   - Clear context\n   - Acceptable variations (jika ada)\n\n4. Matching Questions (10%)\n   - 5-7 items to match\n   - Clear categories\n   - Logical pairs\n\n5. Short Answer Questions (10%)\n   - Open-ended but specific\n   - Rubric untuk grading\n   - Expected key points\n\n6. Scenario-based Questions (5%)\n   - Real-world situations\n   - Problem-solving required\n   - Multiple steps atau considerations\n\nOutput Format:\n- Question number dan text\n- Options (untuk MCQ)\n- Correct answer\n- Explanation/rationale\n- Difficulty level\n- Bloom's Taxonomy level (Remember/Understand/Apply/Analyze/Evaluate/Create)\n\nAdditional Features:\n- Score calculation formula\n- Feedback messages (untuk passing/failing)\n- Review mode suggestions\n- Study tips based on performance",
  },
  {
    id: "23",
    title: "Study Guide Generator",
    cover: "/images/covers/edukasi-category.png",
    slug: "study-guide-generator",
    category: "edukasi",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat study guide yang komprehensif untuk persiapan ujian atau pembelajaran.",
    content: "Buat study guide untuk [Mata Pelajaran/Topik] untuk persiapan [Jenis Ujian: UAS/UTS/UN/CPNS/TOEFL].\n\nStudy Guide Structure:\n\n1. Overview & Learning Objectives\n   - Key topics yang akan dibahas\n   - What students should know by the end\n   - Importance of the material\n\n2. Key Concepts & Definitions\n   - Important terms dengan definitions\n   - Formulas atau equations (jika relevan)\n   - Theorems atau principles\n   - Mnemonics atau memory aids\n\n3. Detailed Content Breakdown\n   - Subtopic 1\n     * Main ideas\n     * Supporting details\n     * Examples\n     * Common mistakes to avoid\n   \n   - Subtopic 2\n     * Main ideas\n     * Supporting details\n     * Examples\n     * Common mistakes to avoid\n   \n   [Continue untuk semua subtopics]\n\n4. Visual Aids\n   - Diagram suggestions\n   - Charts atau graphs\n   - Mind maps structure\n   - Flowcharts untuk processes\n\n5. Practice Questions\n   - Review questions per section\n   - Application problems\n   - Critical thinking questions\n   - Answer key dengan explanations\n\n6. Study Strategies\n   - Recommended study schedule\n   - Active recall techniques\n   - Spaced repetition tips\n   - Group study suggestions\n\n7. Resources & References\n   - Textbook chapters\n   - Online resources\n   - Videos atau podcasts\n   - Practice tests\n\n8. Self-Assessment Checklist\n   - \"I can...\" statements\n   - Confidence ratings\n   - Areas needing more review\n\nFormat:\n- Use headings dan subheadings\n- Bullet points untuk clarity\n- Bold important terms\n- Include examples untuk setiap concept\n- Add tips atau notes dalam boxes",
  },
  {
    id: "24",
    title: "Educational Content Script",
    cover: "/images/covers/edukasi-category.png",
    slug: "educational-content-script",
    category: "edukasi",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Buat script untuk konten edukasi (video, podcast, atau presentation).",
    content: "Tulis script edukasi untuk [Format: video/podcast/presentation] tentang topik [Topik] untuk audience [Target Audience: siswa/usia/demografi].\n\nScript Specifications:\n- Duration: [Durasi: 5-10 menit/15-20 menit]\n- Tone: [Formal/Santai/Entertaining/Energetic]\n- Learning objectives: [3-5 objectives]\n\nScript Structure:\n\n[0:00-0:30] INTRODUCTION\n- Hook yang menarik perhatian\n- State the topic dan relevance\n- Preview what akan dipelajari\n- Establish credibility (jika perlu)\n\n[0:30-2:00] FOUNDATION\n- Define key terms\n- Provide necessary background\n- Connect to prior knowledge\n- Set the stage untuk main content\n\n[2:00-8:00] MAIN CONTENT (divide into 2-3 segments)\nSegment 1: [Subtopic 1]\n- Explain concept dengan examples\n- Use analogies atau metaphors\n- Include visual/audio cues\n- Check for understanding\n\nSegment 2: [Subtopic 2]\n- Build on previous segment\n- Introduce new information\n- Provide demonstrations\n- Address common questions\n\nSegment 3: [Subtopic 3]\n- Deepen understanding\n- Show applications\n- Include interactive elements\n\n[8:00-9:30] APPLICATION & EXAMPLES\n- Real-world applications\n- Case studies atau scenarios\n- Problem-solving demonstration\n- Show relevance to audience\n\n[9:30-10:00] SUMMARY & CONCLUSION\n- Recap key points\n- Reinforce main takeaways\n- Answer \"So what?\" question\n- Call-to-action atau next steps\n\nAdditional Elements:\n- Pauses untuk emphasis\n- Transition phrases antar segments\n- Questions to engage audience\n- Visual/audio suggestions\n- Timing cues\n- Speaker notes (jika presentasi)\n\nAccessibility Considerations:\n- Transcript availability\n- Closed captioning cues\n- Descriptive audio notes",
  },
  {
    id: "25",
    title: "Curriculum Development",
    cover: "/images/covers/edukasi-category.png",
    slug: "curriculum-development",
    category: "edukasi",
    rekomAI: [ "ChatGPT", "Claude" ],
    description: "Rancang kurikulum lengkap untuk kursus atau program pembelajaran.",
    content: "Rancang kurikulum untuk [Nama Kursus/Program] yang ditujukan untuk [Target Audience] dengan durasi [Durasi: 4 minggu/8 minggu/1 semester].\n\nProgram Overview:\n- Program title dan description\n- Target learning outcomes\n- Prerequisites (jika ada)\n- Certification atau credentials yang diberikan\n\nCurriculum Structure:\n\nModule 1: [Module Title]\n- Duration: [Jumlah minggu/sesi]\n- Learning Objectives:\n  * Objective 1\n  * Objective 2\n  * Objective 3\n- Topics Covered:\n  * Topic 1.1\n  * Topic 1.2\n  * Topic 1.3\n- Activities & Assignments:\n  * Activity 1\n  * Assignment 1\n  * Project/Case Study\n- Assessment Methods:\n  * Quiz/Exam\n  * Participation\n  * Project evaluation\n\nModule 2: [Module Title]\n[Same structure as Module 1]\n\nModule 3: [Module Title]\n[Same structure as Module 1]\n\n[Continue untuk semua modules]\n\nTeaching Methodology:\n- Lecture format (live/recorded)\n- Discussion forums\n- Group projects\n- Hands-on labs/practices\n- Guest speakers (jika relevan)\n- Field trips/virtual tours\n\nAssessment Strategy:\n- Formative assessments (quizzes, assignments)\n- Summative assessments (midterm, final project)\n- Participation grading\n- Peer evaluation (jika ada)\n- Rubrics untuk project grading\n\nResources & Materials:\n- Required textbooks atau readings\n- Online resources dan links\n- Software/tools yang diperlukan\n- Templates atau frameworks\n- Sample projects\n\nSchedule Template:\n- Weekly breakdown\n- Important deadlines\n- Office hours\n- Review sessions\n- Exam dates\n\nInstructor Guidelines:\n- Teaching tips per module\n- Common student questions\n- Grading guidelines\n- Time management suggestions\n\nStudent Support:\n- Office hours schedule\n- Discussion forum guidelines\n- Technical support contacts\n- Academic integrity policy\n- Accessibility accommodations\n\nEvaluation & Improvement:\n- Course evaluation survey\n- Learning analytics to track\n- Continuous improvement process\n- Feedback collection methods",
  },
];